In [5]:
from gensim.models import word2vec
import nltk
import pandas as pd 
import numpy as np
import re 
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer


In [6]:
path = r"C:\Users\ismai\Desktop\Deep Learning\NLP\sentiment labelled sentences"

In [7]:
pd.read_csv(f"{path}\yelp_labelled.txt",delimiter ='\t',header=None)

0  1
0                             Wow... Loved this place.  1
1                                   Crust is not good.  0
2            Not tasty and the texture was just nasty.  0
3    Stopped by during the late May bank holiday of...  1
4    The selection on the menu was great and so wer...  1
..                                                 ... ..
995  I think food should have flavor and texture an...  0
996                           Appetite instantly gone.  0
997  Overall I was not impressed and would not go b...  0
998  The whole experience was underwhelming, and I ...  0
999  Then, as if I hadn't wasted enough of my life ...  0

[1000 rows x 2 columns]

In [8]:
websites = ['amazon_cells_labelled.txt','yelp_labelled.txt','imdb_labelled.txt']

In [9]:
df = pd.DataFrame()
for website in websites:
    website_df = pd.read_csv(f"{path}/{website}",delimiter ='\t',header = None)
    df = pd.concat([df,website_df],axis = 0)

In [10]:
df.columns = ['Review','Sentiment']

In [11]:
def text_preprocessor(doc):
    doc = doc.lower().strip()
    try:
        doc = doc.replace('.',". ")
        doc = doc.replace(',',", ")
        doc = doc.replace('!',"! ")
    except:
        pass
    doc = re.sub(r"[^a-z\s]","",doc) #to rmv space and anything not lower
    doc = [d.strip() for d in doc.split() if d not in stopwords]
    doc = " ".join(doc)
    return doc

In [12]:
stopwords = nltk.corpus.stopwords.words('English')

In [13]:
df['Cleaned_review']=df['Review'].apply(text_preprocessor)

In [14]:
df['Cleaned_review']

0                        way plug us unless go converter
1                              good case excellent value
2                                          great jawbone
3      tied charger conversations lasting minutes maj...
4                                              mic great
                             ...                        
743        got bored watching jessice lange take clothes
744    unfortunately virtue films production work los...
745                                    word embarrassing
746                                    exceptionally bad
747            insult ones intelligence huge waste money
Name: Cleaned_review, Length: 2748, dtype: object

In [15]:
sentences = [review.split() for review in df['Cleaned_review']] 

In [16]:
sentences

[['way', 'plug', 'us', 'unless', 'go', 'converter'],
 ['good', 'case', 'excellent', 'value'],
 ['great', 'jawbone'],
 ['tied',
  'charger',
  'conversations',
  'lasting',
  'minutes',
  'major',
  'problems'],
 ['mic', 'great'],
 ['jiggle', 'plug', 'get', 'line', 'right', 'get', 'decent', 'volume'],
 ['several',
  'dozen',
  'several',
  'hundred',
  'contacts',
  'imagine',
  'fun',
  'sending',
  'one',
  'one'],
 ['razr', 'owner', 'must'],
 ['needless', 'say', 'wasted', 'money'],
 ['waste', 'money', 'time'],
 ['sound', 'quality', 'great'],
 ['impressed', 'going', 'original', 'battery', 'extended', 'battery'],
 ['two',
  'seperated',
  'mere',
  'ft',
  'started',
  'notice',
  'excessive',
  'static',
  'garbled',
  'sound',
  'headset'],
 ['good', 'quality', 'though'],
 ['design', 'odd', 'ear', 'clip', 'comfortable'],
 ['highly', 'recommend', 'one', 'blue', 'tooth', 'phone'],
 ['advise', 'everyone', 'fooled'],
 ['far', 'good'],
 ['works', 'great'],
 ['clicks',
  'place',
  'way',


In [17]:
word_vec = word2vec.Word2Vec(sentences,epochs=10,sg = 1,vector_size =100,min_count =1,window =5,workers =1)

In [18]:
word_vec.wv.index_to_key #in decreasing order

['good',
 'great',
 'movie',
 'phone',
 'film',
 'one',
 'food',
 'like',
 'place',
 'time',
 'service',
 'really',
 'bad',
 'well',
 'dont',
 'would',
 'best',
 'ever',
 'even',
 'also',
 'back',
 'quality',
 'go',
 'love',
 'ive',
 'made',
 'im',
 'product',
 'get',
 'work',
 'nice',
 'better',
 'could',
 'excellent',
 'works',
 'never',
 'recommend',
 'much',
 'use',
 'sound',
 'think',
 'headset',
 'first',
 'battery',
 'way',
 'see',
 'pretty',
 'make',
 'didnt',
 'acting',
 'worst',
 'still',
 'got',
 'everything',
 'characters',
 'enough',
 'say',
 'two',
 'disappointed',
 'ear',
 'every',
 'little',
 'thing',
 'amazing',
 'price',
 'right',
 'going',
 'people',
 'minutes',
 'waste',
 'definitely',
 'terrible',
 'real',
 'case',
 'look',
 'money',
 'movies',
 'came',
 'new',
 'cant',
 'know',
 'experience',
 'friendly',
 'story',
 'many',
 'doesnt',
 'wont',
 'far',
 'poor',
 'used',
 'piece',
 'worth',
 'films',
 'plot',
 'nothing',
 'seen',
 'years',
 'life',
 'us',
 'wonderfu

In [19]:
words = word_vec.wv.index_to_key

In [20]:
word_vectors = word_vec.wv.vectors

In [21]:
word_vec.wv['good']

array([-1.31814525e-01,  2.35518441e-01,  5.61752804e-02,  5.24918772e-02,
       -1.12923933e-02, -3.90702248e-01,  1.13617957e-01,  3.75881612e-01,
       -1.38282269e-01, -2.00778902e-01, -2.77259164e-02, -3.81579936e-01,
       -1.73157535e-03,  2.31807008e-02,  2.17122142e-04, -1.88861921e-01,
        1.92678437e-01, -3.20992440e-01, -3.70990112e-02, -3.86446565e-01,
        2.06787154e-01,  1.35260031e-01,  2.07829356e-01, -1.57708544e-02,
       -1.18281722e-01, -3.33276615e-02, -3.89624722e-02, -1.56096950e-01,
       -1.78872183e-01, -4.86992039e-02,  2.90176779e-01,  2.77122669e-02,
       -1.98902488e-02, -1.86711058e-01,  1.43503854e-02,  2.99700409e-01,
        1.43148452e-01, -1.59251541e-01, -2.05993026e-01, -4.27152336e-01,
        7.16654360e-02, -2.80167967e-01,  2.18468648e-03, -4.74916361e-02,
        1.77966371e-01, -1.78579107e-01, -2.42277846e-01, -3.78778614e-02,
        1.00137666e-01,  1.91937208e-01,  4.15820032e-02, -1.81893006e-01,
       -3.88505720e-02,  

In [22]:
word_vectors.shape

(5105, 100)

In [23]:
vocab_size,vec_size = word_vectors.shape

In [24]:
word_vec.wv.most_similar('good')

[('nice', 0.9974832534790039),
 ('cheap', 0.9974063634872437),
 ('clean', 0.997371256351471),
 ('really', 0.9973598122596741),
 ('menu', 0.9973145127296448),
 ('bit', 0.9972962141036987),
 ('food', 0.997234046459198),
 ('high', 0.9972166419029236),
 ('thats', 0.9971973299980164),
 ('bland', 0.9971833825111389)]

In [25]:
X = df['Cleaned_review']
y = df['Sentiment']

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)

In [28]:
X_train

579    due happening every call forced stop using hea...
178        weekly haunt definitely place come back every
829                                  really good product
452    colleague get great reception little expensive...
870         started review two stars im editing give one
                             ...                        
960    exchanged sony ericson za im pretty happy deci...
905        nearly good looking amazon picture makes look
96                                                  back
235                          one favorite purchases ever
61                       place receives stars appetizers
Name: Cleaned_review, Length: 2198, dtype: object

In [57]:
X_train.shape

(2198, 100)

In [29]:
#convert x_train to numbers using tokenizer
#embedding layers is expecting positive numbers and tokenizer will give us positive num
#wordvec gives float

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

In [30]:
tokenizer.word_index

{'good': 1,
 'great': 2,
 'phone': 3,
 'movie': 4,
 'film': 5,
 'one': 6,
 'like': 7,
 'place': 8,
 'food': 9,
 'time': 10,
 'service': 11,
 'really': 12,
 'well': 13,
 'bad': 14,
 'would': 15,
 'ever': 16,
 'best': 17,
 'dont': 18,
 'also': 19,
 'even': 20,
 'back': 21,
 'quality': 22,
 'go': 23,
 'ive': 24,
 'better': 25,
 'love': 26,
 'made': 27,
 'im': 28,
 'get': 29,
 'nice': 30,
 'product': 31,
 'work': 32,
 'use': 33,
 'much': 34,
 'works': 35,
 'never': 36,
 'could': 37,
 'recommend': 38,
 'way': 39,
 'think': 40,
 'headset': 41,
 'battery': 42,
 'sound': 43,
 'pretty': 44,
 'excellent': 45,
 'see': 46,
 'didnt': 47,
 'got': 48,
 'first': 49,
 'still': 50,
 'acting': 51,
 'case': 52,
 'make': 53,
 'look': 54,
 'little': 55,
 'ear': 56,
 'right': 57,
 'characters': 58,
 'worst': 59,
 'friendly': 60,
 'going': 61,
 'disappointed': 62,
 'came': 63,
 'two': 64,
 'say': 65,
 'amazing': 66,
 'everything': 67,
 'minutes': 68,
 'new': 69,
 'people': 70,
 'terrible': 71,
 'money': 72,
 

In [31]:
len(tokenizer.word_index)

4350

In [32]:
#to transform tokenizer to x_train andX_test
X_train = tokenizer.texts_to_sequences(X_train)
X_test = tokenizer.texts_to_sequences(X_test)

In [46]:
tokenizer.word_index.items()

dict_items([('good', 1), ('great', 2), ('phone', 3), ('movie', 4), ('film', 5), ('one', 6), ('like', 7), ('place', 8), ('food', 9), ('time', 10), ('service', 11), ('really', 12), ('well', 13), ('bad', 14), ('would', 15), ('ever', 16), ('best', 17), ('dont', 18), ('also', 19), ('even', 20), ('back', 21), ('quality', 22), ('go', 23), ('ive', 24), ('better', 25), ('love', 26), ('made', 27), ('im', 28), ('get', 29), ('nice', 30), ('product', 31), ('work', 32), ('use', 33), ('much', 34), ('works', 35), ('never', 36), ('could', 37), ('recommend', 38), ('way', 39), ('think', 40), ('headset', 41), ('battery', 42), ('sound', 43), ('pretty', 44), ('excellent', 45), ('see', 46), ('didnt', 47), ('got', 48), ('first', 49), ('still', 50), ('acting', 51), ('case', 52), ('make', 53), ('look', 54), ('little', 55), ('ear', 56), ('right', 57), ('characters', 58), ('worst', 59), ('friendly', 60), ('going', 61), ('disappointed', 62), ('came', 63), ('two', 64), ('say', 65), ('amazing', 66), ('everything', 6

In [33]:
X_train

[[611, 1703, 82, 309, 1066, 764, 226, 41],
 [1704, 1705, 78, 8, 125, 21, 82],
 [12, 1, 31],
 [1706, 29, 2, 274, 55, 612, 201, 2],
 [275, 410, 64, 126, 28, 499, 95, 6],
 [500, 26, 501],
 [765, 15, 17, 39, 1067],
 [502, 1707, 72, 1708, 73],
 [613, 56, 1068, 1069, 17],
 [156],
 [1709, 42, 503, 1710, 227, 504],
 [1711, 60],
 [5, 27],
 [41, 1712, 1713, 96, 157],
 [17, 614, 505, 83],
 [2, 615, 1714, 1715, 766, 506, 310, 180, 33, 1716, 1717, 766, 1718, 767],
 [1719, 1070, 11, 228, 768, 158, 1720, 411, 86, 61, 21],
 [142],
 [1721, 1722, 1723, 17, 74, 229],
 [20, 1071, 616, 111, 1724, 504, 507, 1072, 1725, 1073, 230, 1726],
 [12, 103, 119, 311, 143, 57, 1074, 1727, 769, 355, 1728],
 [276, 1729, 127, 617, 32, 356, 1730, 128],
 [231, 159, 255],
 [11, 1, 357, 25],
 [30, 358],
 [11, 508, 20, 23, 770, 7, 7],
 [34, 65, 8, 509, 412, 66, 359, 62],
 [3, 771, 277],
 [86, 32, 57, 1731],
 [46, 127],
 [129, 618, 1732, 1733],
 [34, 181, 510, 360, 256, 1734, 1735],
 [1736, 361, 2, 1075, 1076, 614, 60, 144],
 

In [47]:
X_train.shape

(2198, 100)

In [50]:
#pad every single senstences to have the same size using pad sequences
pad_sequences?


In [58]:
X_train = pad_sequences(X_train,maxlen = vec_size,padding = 'post')
X_test = pad_sequences(X_test,maxlen = vec_size,padding = 'post')

In [59]:
X_train

array([[ 611, 1703,   82, ...,    0,    0,    0],
       [1704, 1705,   78, ...,    0,    0,    0],
       [  12,    1,   31, ...,    0,    0,    0],
       ...,
       [  21,    0,    0, ...,    0,    0,    0],
       [   6,  524, 4349, ...,    0,    0,    0],
       [   8, 4350,  126, ...,    0,    0,    0]])

In [60]:
X_train[0]

array([ 611, 1703,   82,  309, 1066,  764,  226,   41,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0])

In [61]:
X_train.shape

(2198, 100)

In [38]:
#wordvec as weight

In [62]:
token_size = len(tokenizer.word_index) + 1

In [63]:
token_size

4351

In [72]:
a = np.zeros((4,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
embedding_matrix = np.zeros((token_size,vec_size))
for word,index in tokenizer.word_index.items():
    if word in word_vec.wv:
        embedding_matrix[index] = word_vec.wv[word]

In [74]:
word_vec.wv

In [43]:
embedding_matrix

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.31814525e-01,  2.35518441e-01,  5.61752804e-02, ...,
        -2.65086204e-01,  9.69012827e-02, -1.19544799e-03],
       [-1.44251511e-01,  2.39836469e-01,  4.84003983e-02, ...,
        -2.61129737e-01,  8.26920643e-02, -1.23599246e-02],
       ...,
       [-3.00984345e-02,  4.54902314e-02,  1.12962836e-04, ...,
        -4.97273728e-02,  2.01679021e-02, -4.32601338e-03],
       [-8.49220622e-03,  1.92739889e-02,  1.14703458e-02, ...,
        -1.80626754e-02,  7.72192702e-03,  2.33535562e-03],
       [-8.44088383e-03,  1.72328185e-02,  9.68292356e-03, ...,
        -2.36082450e-02,  9.68559831e-03, -4.17269766e-03]])

# RNN

In [75]:
from tensorflow.keras.layers import Embedding, Dense, Dropout, LSTM, SimpleRNN,Flatten
from tensorflow.keras.models import Sequential

In [76]:
model = Sequential()
model.add(Embedding(input_dim = token_size,output_dim = vec_size,input_length = vec_size,
                    weights = [embedding_matrix]))
model.add(LSTM(units=256,dropout = 0.3,recurrent_dropout = 0.2,return_sequences = True))
model.add(LSTM(units=128,return_sequences = True))
model.add(Flatten())
model.add(Dense(units=1,activation = 'sigmoid'))

In [ ]:
Embedding?

In [77]:
y.value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [78]:
model.compile(loss='binary_crossentropy',optimizer = 'adam',metrics =['accuracy'])

In [79]:
model.fit(X_train,y_train,epochs= 30,validation_split = 0.15,verbose = 1)

Epoch 1/30
59/59 [==============================] - 49s 726ms/step - loss: 0.6945 - accuracy: 0.5166 - val_loss: 0.6839 - val_accuracy: 0.5758
Epoch 2/30
59/59 [==============================] - 41s 690ms/step - loss: 0.5107 - accuracy: 0.7645 - val_loss: 0.5432 - val_accuracy: 0.7485
Epoch 3/30
59/59 [==============================] - 42s 703ms/step - loss: 0.1935 - accuracy: 0.9245 - val_loss: 0.7717 - val_accuracy: 0.7455
Epoch 4/30
59/59 [==============================] - 42s 706ms/step - loss: 0.0987 - accuracy: 0.9647 - val_loss: 0.7684 - val_accuracy: 0.7606
Epoch 5/30
59/59 [==============================] - 41s 700ms/step - loss: 0.0798 - accuracy: 0.9732 - val_loss: 0.7162 - val_accuracy: 0.7485
Epoch 6/30
59/59 [==============================] - 42s 706ms/step - loss: 0.0572 - accuracy: 0.9802 - val_loss: 0.8159 - val_accuracy: 0.7424
Epoch 7/30
59/59 [==============================] - 41s 702ms/step - loss: 0.0439 - accuracy: 0.9855 - val_loss: 1.0511 - val_accuracy: 0.7333

In [80]:
model.evaluate(X_test,y_test)

18/18 [==============================] - 2s 96ms/step - loss: 1.3985 - accuracy: 0.7836


[1.3985083103179932, 0.7836363911628723]

In [82]:
prob = model.predict(X_test)

18/18 [==============================] - 2s 96ms/step


In [87]:
y_pred = [int(p >= 0.5)  for p in prob]

In [88]:
y_pred

[1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
